### ISSUE TITLE
support RFC 6991 hex-string and related

### ISSUE THREAD

**Issue by cabo** [cabo/yang-standin#5]
RFC 6991 defines hex-string as well as the related phys-address and mac-address.
They all are hex-strings built out of 2 hex digits per byte, with colons (':') interspersed.

mac-address is exactly 6 bytes:

         pattern '[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}';

hex-string and phys-address are zero or more bytes:

         pattern '([0-9a-fA-F]{2}(:[0-9a-fA-F]{2})*)?';

Wo do have tag 48 for a MAC address in this hex-string form, but this probably could cause validation issues if we use that for lengths not allowed for MAC addresses.

hex-strings are canonically lower-case, but upper-case is allowed as well.  Not sure what the incidence for upper case is.  Might need two new tags: hex-string (lower case), hex-string (upper case).

**Comment by marenamat** [comment]
i would favor converting hex strings to binary blobs, dropping the lower/upper case thing altogether

there is certain semantics in the data and abusing the specs to store _something_ in the upper/lower case is just adding unnecessary problems

if somebody insists on keeping irrelevant information in the data, they shall stay with legacy

**Comment by cabo** [comment]
Im pretty sure we do not want to create a situation where we encode uppercase/lowercase together with the actual binary (byte string) data.
However, we need to make some recommendations how to cope with non-canonical representations in an intermediate encoder; I would lean towards encouraging aggressive encoding (i.e., lose the difference), but enabling keeping legacy encoding for encoders that are not legacy-eschewing.
That difference needs to be part of our negotiation model, so constrained implementations (that are likely to be legacy-eschewing encoders as well as intolerant decoders) get good support.
